# Override pour le développement
# Utilisé automatiquement avec docker-compose up

version: '3.8'

services:
  # Volumes pour le développement
  sonarqube:
    volumes:
      - ./custom-rules:/opt/sonarqube/custom-rules
  
  # Variables d'environnement de dev
  carbon-calculator:
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
